"""Phase 10 - All models

Revision ID: 90552c584965
Revises: 
Create Date: 2025-11-30 13:33:39.664989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90552c584965'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('example_answer', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('interviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('actual_duration', sa.Integer(), nullable=True),
    sa.Column('video_url_cam0', sa.String(length=500), nullable=True),
    sa.Column('video_url_cam1', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_interviews_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('job_role', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('ai_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('prompt_global', sa.Text(), nullable=True),
    sa.Column('prompt_interview', sa.Text(), nullable=True),
    sa.Column('prompt_coach', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('analysis_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('interview_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('empathy_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('clarity_score', sa.Float(), nullable=True),
    sa.Column('emotion_data', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_reports_interview_id'), ['interview_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_reports_interview_id'))

    op.drop_table('analysis_reports')
    op.drop_table('user_settings')
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_interviews_created_at'))

    op.drop_table('interviews')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('questions')
    # ### end Alembic commands ###
